# Generated by Django 5.1.1 on 2024-10-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='tipo',
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(default='Característica', max_length=100),
        ),
        migrations.DeleteModel(
            name='TipoCaracteristica',
        ),
    ]
